# Generated by Django 4.1.7 on 2023-02-18 14:47

import core.utilis
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sizes_allowed', models.CharField(max_length=100, validators=[core.utilis.validate_sizes_allowed])),
                ('store_original', models.BooleanField(default=False)),
                ('allow_link', models.BooleanField(default=False)),
            ],
        ),
    ]
